apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
   name: oai-nrf
spec:
  lookupPolicy:
    local: true
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: "oai-nrf"
spec:
    runPolicy: "Serial"
    source:
        type: "Binary"
        secrets:
          - secret:
              name: etc-pki-entitlement
            destinationDir: etc-pki-entitlement
        configMaps:
          - configMap:
              name: rhsm-conf
            destinationDir: rhsm-conf
          - configMap:
              name: rhsm-ca
            destinationDir: rhsm-ca
    strategy:
        dockerStrategy:
            dockerfilePath: "docker/Dockerfile.nrf.rhel8.2"
            buildArgs:
                - name: "NEEDED_GIT_PROXY"
                  value: "http://proxy.eurecom.fr:8080"
    output:
        to:
            kind: "ImageStreamTag"
            name: "oai-nrf:develop"
