/**
* NRF NFDiscovery Service
* NRF NFDiscovery Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.1.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "StoredSearchDocumentApiImpl.h"

namespace oai {
namespace nrf {
namespace api {

using namespace oai::nrf::model;

StoredSearchDocumentApiImpl::StoredSearchDocumentApiImpl(std::shared_ptr<Pistache::Rest::Router> rtr)
    : StoredSearchDocumentApi(rtr)
    { }

void StoredSearchDocumentApiImpl::retrieve_stored_search(const std::string &searchId, Pistache::Http::ResponseWriter &response) {
    response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}

}
}
}

