/**
* NRF NFDiscovery Service
* NRF NFDiscovery Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.1.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
* StoredSearchDocumentApiImpl.h
*
* 
*/

#ifndef STORED_SEARCH_DOCUMENT_API_IMPL_H_
#define STORED_SEARCH_DOCUMENT_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <StoredSearchDocumentApi.h>

#include <pistache/optional.h>

#include "StoredSearchResult.h"
#include <string>

namespace oai {
namespace nrf {
namespace api {

using namespace oai::nrf::model;

class StoredSearchDocumentApiImpl : public oai::nrf::api::StoredSearchDocumentApi {
public:
    StoredSearchDocumentApiImpl(std::shared_ptr<Pistache::Rest::Router>);
    ~StoredSearchDocumentApiImpl() {}

    void retrieve_stored_search(const std::string &searchId, Pistache::Http::ResponseWriter &response);

};

}
}
}



#endif