/**
 * NRF NFManagement Service
 * NRF NFManagement Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "SubscriptionIDDocumentApiImpl.h"

namespace oai {
namespace nrf {
namespace api {

using namespace oai::nrf::model;

SubscriptionIDDocumentApiImpl::SubscriptionIDDocumentApiImpl(
    std::shared_ptr<Pistache::Rest::Router> rtr, oai::nrf::nrf_app *nrf_app_inst,
    std::string address)
    :
    SubscriptionIDDocumentApi(rtr),
    m_nrf_app(nrf_app_inst),
    m_address(address) {
}

void SubscriptionIDDocumentApiImpl::remove_subscription(
    const std::string &subscriptionID,
    Pistache::Http::ResponseWriter &response) {
  response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}
void SubscriptionIDDocumentApiImpl::update_subscription(
    const std::string &subscriptionID, const std::vector<PatchItem> &patchItem,
    Pistache::Http::ResponseWriter &response) {
  response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}

}
}
}

