/**
* NRF NFManagement Service
* NRF NFManagement Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.1.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "SubscriptionsCollectionApiImpl.h"

namespace oai {
namespace nrf {
namespace api {

using namespace oai::nrf::model;

SubscriptionsCollectionApiImpl::SubscriptionsCollectionApiImpl(std::shared_ptr<Pistache::Rest::Router> rtr)
    : SubscriptionsCollectionApi(rtr)
    { }

void SubscriptionsCollectionApiImpl::create_subscription(const SubscriptionData &subscriptionData, Pistache::Http::ResponseWriter &response) {
    response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}

}
}
}

